# Generated by Django 5.1.4 on 2025-01-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
