# Generated by Django 5.1.4 on 2025-01-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ordermodel_address_ordermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='is_delivery',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
